web:
  build: ./php/
  ports:
    - "80:80"
    - "443:443"
  links:
    - db
  volumes:
    - ./sites:/var/www/html
    - ./sites-enabled:/etc/apache2/sites-enabled
db:
  image: "mysql:5.7" 
  # or mysql:5.6, mysql:8 @see https://github.com/docker-library/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
